### ISSUE TITLE
Search pages

### ISSUE THREAD

**Issue by zanhk** [velsa/notehost#11]
Is it possible to have the search functionlity like there is on the published notion site?

![image](https://github.com/velsa/notehost/assets/17980844/6667d6f8-49fa-485b-80ec-884b2f2ea052)

Thanks

**Comment by velsa** [comment]
Unfortunately, I can't think of a simple solution for this. 
If we keep the original Notion search on the page - it will allow the user to search through ALL of your public pages, even those that are not 'officially' hosted on your domain. 

If you need advanced functionality like search or other interactivity, I suggest you consider the next level solutions like super.so, potion.so and the likes.

**Comment by zanhk** [comment]
Ok thanks
