### ISSUE TITLE
How to setup 404 page?

### ISSUE THREAD

**Issue by zanhk** [velsa/notehost#12]
I setted the 404 page in the configuration like so

```
fof: {
        page: "78b0d54f81124f6584c0aa3d73431963",
        slug: "404", // default
    },
```

the page is a published page where the slug work correctly https://majestico.dev/404

but if I put a non existing url it show the notion 404 page

https://majestico.dev/asdfasdfa

![image](https://github.com/velsa/notehost/assets/17980844/af3952f6-265d-4d13-b1ad-66c95dbd88e2)

How can i show the created 404 page?

**Comment by velsa** [comment]
The latest version of notehost (1.0.14) should fix the fof issue.

Please update your notehost package and redeploy your website.

**Comment by zanhk** [comment]
Thanks @velsa! Can confirm in fact that it works
