### ISSUE TITLE
Optimal way to add footer

### ISSUE THREAD

**Issue by zanhk** [velsa/notehost#15]
This should be a discussion but discussions are not enabled on this repo.

Right now I'm appending the footer like that

```js
// TODO: improve, right now I don't know if the notion app has been loaded
    setInterval(() => {
        let targetElement = document.querySelector(".notion-scroller.vertical");
        targetElement?.appendChild(footer);
    }, 1500);
```

https://majestico.dev/

that's obviusly not the right way to do so and it doesn't behave correctly all the time, how do you guys handle the footer?

Thanks

**Comment by velsa** [comment]
I've enabled discussions. 

Hope this will help with your question :)

**Comment by zanhk** [comment]
Thanks, moved to discussions https://github.com/velsa/notehost/discussions/19
