### ISSUE TITLE
Hitting the refresh button causes "NoteHost: Page Not found (404)."

### ISSUE THREAD

**Issue by stanimirpehlivanov** [velsa/notehost#22]
Hitting the refresh button on any sub-page causes "NoteHost: Page Not found (404)."

- Adding a slugToPage entry fixes the problem, however the pages that do not have it always yield 404

Steps to reproduce:

1. Setup Notehost with a single slugToPage which points to the notion page ID of the home page and deploy.
2. Embed a second page on that home page. Let's call it page "X"
3. Open your page via the domain and then follow the link to navigate to page "X". Should load ok.
4. Press refresh button. This is where I see "NoteHost: Page Not found (404)." and this replicates consistently.

Any idea how to resolve this?

**Comment by velsa** [comment]
I am a bit confused. If you don't have a slug to page defined for a specific route, the default behavior is to show the 404 page. What do you expect should happen?

**Comment by stanimirpehlivanov** [comment]
Let me clarify. This is a notion page that is accessible and loads correctly on first load via a link on the root. The specific problem occurs only after hitting the refresh button on an already loaded page.

Steps to reproduce:
1. Setup Notehost with a single slugToPage which points to the notion page ID of the home page and deploy.
2. Embed a second page on that home page. Let's call it page "X"
3. Open your page via the domain and then follow the link to navigate to page "X". Should load ok.
4. Press refresh button. This is where I see "NoteHost: Page Not found (404)." and this replicates consistently.

**Comment by velsa** [comment]
I've made a few changes that should address this issue.

Can you please test it with the latest version of notehost?
