### ISSUE TITLE
Receiving Invalid SSL Certificate Error

### ISSUE THREAD

**Issue by DudeThatsErin** [velsa/notehost#24]
I'm attempting to set this up on https://appseeker.org

This is my `site-config.ts`
```typescript
import { NoteHostSiteConfig, googleTag } from 'notehost'
import { PAGE_SCRIPT_JS_STRING } from './_page-script-js-string'

// Set this to your Google Tag ID from Google Analytics
const GOOGLE_TAG_ID = 'G-TSTxxx'

export const SITE_CONFIG: NoteHostSiteConfig = {
  domain: 'appseeker.org',

  // Metatags, optional
  // For main page link preview
  siteName: 'App Seeker',
  siteDescription: 'A place to seek out the perfect app for you.',
  siteImage: 'https://imgur.com/9d1XBIl.png',

  // URL to custom favicon.ico
  siteIcon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAACa5JREFUWEellwtUVHUex7/3MXcYZhheYyICkogIKDDIDA9BUctTVpt7ym3r7KNs9+xm267VOZ06vawttnKjjrWeYwSGaYpooZVvRRMFSQphyTBJEFMgBpj34z7+e/53BpFkrXbvnHnce+7///v8vr/f/f1+w+D/PJYvXy7U1tYG/tdtmIkWfnzTTUlEdK9xuV0CwzKMLAOiyEg7ey9U1g0P76Fr7rzrrvwLFy68oLhdyRoeZafazrwPgPxckAkBqooX5idFiU3E54WkAKIE9Nn92NY/tOFg36UVBaWlzzsG+p95OErHZxh0+MeAA2cDcj08nqXd3d2+nwMxIcDjixdbinl3s+xxI6Aw8PgVfD/ixWHCVn8fP+m4cLnvrecTTNpcQxhERYEDQPmAHfVO35pwXnilo6Nj6KdCTAhwf1GRZWFYoFnyuOAMEDjcEnoJiyMc758FSftiggmxWg0OKyLcIMiXARPHo2LIhS0j3h5FlMq6u7re+SkQEwKsvOUWS5Z/oNllt8PukTEgMjjJ8jDrNHg6Lgp+lsEJHY8YawZKbl+AvtOdsG/eh0SF4FOXH/8adHrccqCk51zPFz8GMSHAs/ffbxE6W5qHbCPo4sPRJQO/0muwIjYSPYyC0zHhmFFqQcmtCxEWoQeR/ehqakVP1SdIHHGhXSJ4fdDpvaxgg2twsMxms33330AmBHhx5UpLX8Oh5g6nD4OCFo9F6LDYqMdXrILupBhYb1sAc0m+mvJyQASggOeB/m97cfqdj2A6ewkOjsPrNidOuX2bBnp6fvuzAFbcu7z4TMeZY4LXi6eijUgSBHypZ+FJT0DpspsxPXMWJEmCIkkAUUAIAVEUcCzgHB7Bl5v3gDv2b2gZDpVODw74xX0aSX7u/PnzzT8EuUaBhIQEHWswHC+AYv6r0QCB59Aaq4VhbhoW3bEQk5OmIuALQFHkoHGFftEPooKwDCBLfrTs/Ay2DxswmTD41BdAjU8UHS5XweDly+PyYhyA2WotHLbbX13GMiW/1+vRzxGcS4pCynwz5i9dgDCDAaI/ABLyGgqBotBAUAWCAPRNYThWQWdjG76u3I14uw9fEIJKr7/dCTzTe+7crlElrgBYiopWumyDb93HsuxSnQ49Og7fpUxC1iILLPOt4AQNJFqRQnLTDYLShwzTb/oKXaNQPMvgwplv0fLuJ4juHkC/hkN1QEKn1//+4IWeB2gKXQGYNSd37n1eR9OSCAP/tVGAP/tGFN86D+nmdMgygSxJ1PY4A0Hnr/aentJwqJqo92o4FsMDNhyr/BjM550IEAb79GH/3NrS+gRdPS4ErxbmrBq2OVelLV+QtPj2+Uz8tKmQRBGKrASL/ChAqOJT+VXJx6kRhBzNCfpT0HDoHxjCm395xTkLzJlFC+LunrPus1667pok3LNqWbL5wQfaJ8XoDKIog1F9UfcLGRo1AMghAIZhrtxAQ6LiqnkZAgFgc/qUjs2blyyb5DrKrD4ihfyhK8cfJ8ofnZr967u+5iWXgUpP05pRJR07qJGAXwQYFjzHAUQGS2Q1H4IbBw3T04BEAIbDiEdUTtdszbr7jR0dV1u8VoGqspr8krl3G7SEbTvVjpaTrWDEgPrI0YPKzghahEVGImtuLlKS41B/qAHdIyI4XgMGDBSiQJYVaFjAAB+mp85EYtIUPF5WsXv7zgO3h6RXaa8BaNz+ZnOmOcOi0wAnjjRiT8UHkOPTwYUb1JupV+EDZxGTdiMy863Iy56B2rrDaJ1yB6ITp0MRRVWJgEKgJ15M/qICxggjiovz8Nyayq+qa/fOvnpuuBagtvz4rJzMojAN0Hy0EYc2fQTm4Xehn5YGQqsfp4FQ+QjCODvSikpgzZ6B7XWH0Zb4S0QnpEIWaZEikGQCHfHihlPrEBGhR1FRHl5+Y0NrZc2e3OsCnNxefnxmTmaRlidoPtqE/e9/BO7P6xA+dQaUgAiZ4SBsegKGMBdm5s+D1ZyqAjRHL0Vk/HQoEgWgCQroWT8SO95FZGQECgpz8ffyDaff27bX/KMAqTmzgwBHGrF344dw/2EdtHEpIH4/JHCIqX0SsXoP0gopwExs23EQn+lvRmQcBRDV7KcAEXwAKd9UIzo6EgWFZrxc/l5rZc3u6yvQtL28ccacjAKBD4Zg38YdcN32BPjYBBAxAImwmHR0HUwmFmn5hbDmpKLmw4PYzS6GMT4FGAUAg0heRFZPNWJiomDJz0HZGxvaN2zbm31dBQ5Xv3QwZ17+IoEnTGP9Ceyv2oIwuoJlwAKQaHZrOERlz0GGxYq8nFTU1R1AuzAX4bHxgKI+4lAIAz0vIbrrE9wwZTLyLFl4umz9yS11BwuvD7D97UxzbvpJloj6JqpA1RYIigxaMWjG+v0ytDotTLnZyLBakDU7BXt2HYR9eAgsywQLVqgu0fuHXD7k5Jphzk2XV79WWbqxdm/DdevA+eb6OGOM/A3PSIbGIyewu5ICKGBYBqKoYPEvkmG/5EQvSUL2PCsseZno67NhxO4MleWxqkgNybKMuMmxYDhOOnD4q5mPPPvS+esC1HeuN5k1ad0sfHoagl0VW8BTBVgGikyQnBoOl5NAmzgLcwqtyLfOhkLdDhWJYBMaX4bpBbvdK279fPcSxDnOrr5316Vx7Xj16tWs0dr2qIfx3Mz5o0YeSP/dMh0PbWN9I+oqtoCTaQiCJcPrkyCECZhekI0MSx6slkyIkhzyfsz41c2LYxmMOFyksq3aY5oWJhMI6565Y+dTVyrhCzuW3AOe3+qxS/DYGDx1y8MwhvE4fqgR29Z/AE6SoSYB6ACiQKsVkGzNxmxLHiyWDIgSHctCo9loL1AbVbAvcAyLEacb61s2whivUa9//537wYrHG6pUtx5aW1wfbtCWulweBGwCXrrnMUSHC2g60oSNb28C8YtqCOh2MgUQBGQUz0V2gQXZOTMREOWxYeSqDjjaqlmGwbDdjbXHqqGE++Gw+cBy3NkMriVdBbjz0ex6UZRLPR43TBE3YO0fn8TFi4M409mLgX4bCK0qQfuqIRqO8IhwmCZFo8SaCo7n1PIbbNljrVPNDQJwHAPbsBN/WvMa/IIHHOERFRO1dn/Vl39TAZY/kp/Rc/Fy2dCQIylpyhQ895tVGee6BrTegAheowmKemUoCLZc2u3olHTjVKMnNdnkoE1ybDhRh8TQHEHnQw5DIy7loZffHHbzg1J0jOm8gTGuaPi0fXjC/wWnj23Mr65pSFIUkfJTc+OGBnpGrxLCMhcvdrWzzoGLfmP0uL20juFx/5TtAk/2R7b5UEtHlbHx4j8GEBxuUo8q2gAAAABJRU5ErkJggg==',

  // Additional safety: avoid serving extraneous Notion content from your website
  // Use the value from your Notion settings => Workspace => Settings => Domain
  notionDomain: 'dudethatserin.notion.site',

  // Map slugs (short page names) to Notion page IDs
  // Empty slug is your main page
  slugToPage: {
    '': '11f1e3d1d62a4b40ae2c0925c0bf5670',
    contact: '9eae95d588544233b8815f8ad2cedb7b',
    about: '724c0d4c08404867a9df09f94bf09fd1',
    browsers: '2d0c6a21dd3b41cc98444e53da9be631',
    'browsers/arc': '9ccf1de38481400e9aeab18fc33d3ebc',
    taskapps: '768496d02e3048a3ab781c9a80a9d600',
    noteapps: '04998cd4c211425e8e945ca457ad1444',
    pwmanagers: '39a7e1354582476ca1278fe0a9c05578'
    // vpn: '' coming soon
    // readlater: '' coming soon
    // calendars: '' coming soon
  },

  // Subdomain redirects are optional
  // But it is recommended to have one for www
  subDomains: {
    www: {
      redirect: 'https://appseeker.org',
    },
  },

  // The 404 (not found) page is optional
  // If you don't have one, the default 404 page will be used
  // fof: {
  //   page: "NOTION_PAGE_ID",
  //   slug: "404", // default
  // },

  // Google Font name, you can choose from https://fonts.google.com
  googleFont: 'Roboto',

  // Custom JS for head and body of a Notion page
  customHeadJS: googleTag(GOOGLE_TAG_ID),
  customBodyJS: PAGE_SCRIPT_JS_STRING,
}
```

I don't understand why I am getting this. Here are some screenshots from CloudFlare for those settings:
<img width="1072" alt="Screenshot 2024-04-05 at 2 33 27 PM" src="https://github.com/velsa/notehost/assets/2681022/cc22ff27-bded-4d2a-a026-a0e53d478205">
<img width="1352" alt="Screenshot 2024-04-05 at 2 34 07 PM" src="https://github.com/velsa/notehost/assets/2681022/39009c55-1620-4448-8562-3c4f1b68bbf5">

I followed the steps I am about to push in a PR as well as published here: https://dudethatserin.notion.site/NoteHost-982d31fcc8dd4799a18efcb074b0e63c?pvs=4

The URL for the page via my notion domain is https://dudethatserin.notion.site/App-Seeker-11f1e3d1d62a4b40ae2c0925c0bf5670?pvs=4

Super odd as I believe that I followed the steps correctly. I am running the deploy command before checking the site and I am checking in an incognito window to make sure it isn't my cookies. I use Google Chrome.

This is a screenshot:
![Screenshot 2024-04-05 at 2 52 09 PM](https://github.com/velsa/notehost/assets/2681022/1d0fdf82-5520-4f0c-8408-95d26118572a)

After doing further troubleshooting, I used [Stephen's old generator](https://fruition-stephenou.vercel.app/) to generate the array for the `NOTION_PAGE_ID` section and this is what I got:
```js
  const SLUG_TO_PAGE = {
    '': '11f1e3d1d62a4b40ae2c0925c0bf5670',
    'about': '724c0d4c08404867a9df09f94bf09fd1',
    'contact': '9eae95d588544233b8815f8ad2cedb7b',
    'browsers': '2d0c6a21dd3b41cc98444e53da9be631',
    'browsers/arc': '2d0c6a21dd3b41cc98444e53da9be631',
    'taskmanagers': '768496d02e3048a3ab781c9a80a9d600',
    'noteapps': '04998cd4c211425e8e945ca457ad1444',
    'pwmanagers': '39a7e1354582476ca1278fe0a9c05578',
  };
```
So, I copied and pasted everything from inside the array, ran the deploy, checked, purged CF cache (after closing the incognito browser), checked again in an incognito browser, and then also checked in Safari (which I never use) and I'm still getting the same error.

I should also add that I tried turning SSL off, trying flexible and strict. None of those options help.

I also tried commenting out the siteIcon (then running deploy) as well as clearing my cookies in Chrome. None of them help. I am out of ideas. It doesn't even go to my custom 404 page that I implemented so something is going on that I have no idea about.
https://dudethatserin.notion.site/404-34333ac547e24d6f919951d1543beb93?pvs=4

![Screenshot 2024-04-05 at 2 59 16 PM](https://github.com/velsa/notehost/assets/2681022/59afbdfb-fc8f-4ee0-a329-32dcd735712e)

LASTEST UPDATE 3:15pm CST on April 5: App Seeker is working but only because I'm using my [old code](https://github.com/stephenou/fruitionsite/issues/258#issue-1929516345). NoteHost is *not* working for me. I am using the same worker so I am able/willing to test code when/if it gets updated. Until then I'm using what I know works.

**Comment by DudeThatsErin** [comment]
> LASTEST UPDATE 3:15pm CST on April 5: App Seeker is working but only because I'm using my [old code](https://github.com/stephenou/fruitionsite/issues/258#issue-1929516345). NoteHost is _not_ working for me. I am using the same worker so I am able/willing to test code when/if it gets updated. Until then I'm using what I know works.

@heyitsmedev I know it is at the very end of a long post but it is right above the comment box.... Either way this is your answer.

**Comment by velsa** [comment]
@DudeThatsErin the config looks ok, except for the part of `notionDomain`

It should be just `dudethatserin`, without the `.notion.site` part – the same way it appears in Notion settings.

Hopefully, this change should fix the SSL error.

**Comment by DudeThatsErin** [comment]
> @DudeThatsErin the config looks ok, except for the part of `notionDomain`
> 
> It should be just `dudethatserin`, without the `.notion.site` part – the same way it appears in Notion settings.
> 
> Hopefully, this change should fix the SSL error.

That did solve it. Thank you! :) I updated the Notion site to note this so hopefully no one else has any issues.
