### ISSUE TITLE
Invalid domain, can't proceed.

### ISSUE THREAD

**Issue by heyitsmedev** [velsa/notehost#27]
Was trying to move from fruitionsite, but it won't work in terminal when I tried to confirm the subdomain..

What could be the issue? Verified subdomain multiple times.

![error](https://github.com/velsa/notehost/assets/122780491/4ebc790f-016d-4618-8dfe-2342da60ef33)

**Comment by velsa** [comment]
I have removed the restriction for specifying subdomains. I didn't test if subdomain hosting will work the same as domain hosting, but I don't think there should be an issue.

To use the new version, just run

```
npx notehost@latest init <subdomain>
```
