### ISSUE TITLE
Tried multiple times, somehow Notion doesn't work. Opens DOMAIN/FULL NOTION URL which is incorrect and shows "no page found"

### ISSUE THREAD

**Issue by ednevsky** [velsa/notehost#32]
Opens the following link: 

![image](https://github.com/velsa/notehost/assets/32431172/8c6e6776-3d32-49eb-be7d-8a8bd10ed090)

**Comment by ednevsky** [comment]
![image](https://github.com/velsa/notehost/assets/32431172/dd231899-5c90-4ac2-8154-a4b0f8de4b10)

**Comment by ednevsky** [comment]
This is the full link Notion ID link in the script in this particular example: Jared-diy-1e4462be3f9c46619956e8fb5b1521e3

**Comment by ednevsky** [comment]
Any ideas on how to fix this? Really wanted to use Notehost for a few sites. @velsa

**Comment by velsa** [comment]
Hey. You need to use only the HEX part of the link. Notion prepends a page name in front of it.

Just use `1e4462be3f9c46619956e8fb5b1521e3` as an ID and it should work.

**Comment by ednevsky** [comment]
@velsa just tried this (and ran npm deploy of course) and it still opens the same type of link (see above). Any other thoughts on why this might be happening? I'm running out of options to try because I have already redone this from scratch. Thanks for the help btw!

Anything else I might try?

**Comment by DudeThatsErin** [comment]
Actually, it works for me.
![image](https://github.com/velsa/notehost/assets/2681022/f7e3167f-4ca0-40f1-8d08-689712a32440)
Clear your cookies.

**Comment by ednevsky** [comment]
Does work now for me too! Awesome. WIll be promoting this now.
