### ISSUE TITLE
Change nameservers to Cloudflare required?

### ISSUE THREAD

**Issue by skilbjo** [velsa/notehost#46]
Hi, I'd like to keep my nameservers on AWS and not transfer them to cloudflare. I'm fine with CNAMEs tho. Is it possible to use notehost without transferring the domain/switching nameservers to cloudflare?

I get this error when running `npm run deploy`

```
> node ./src/_build-page-script-js-string.js

Page script was built successfully!

 ⛅️ wrangler 3.82.0
-------------------

Total Upload: 26.41 KiB / gzip: 7.13 KiB
Uploaded mysite-code-notion-proxy (2.01 sec)

✘ [ERROR] A request to the Cloudflare API (/accounts/6cf9 [[ redacted ]] 26eb7a/workers/scripts/mysite-com-notion-proxy/domains/changeset?replace_state=true) failed.

  workers.api.error.zone_not_specified - Can't infer zone from route, please specify
  zone for "mysite.com" [code: 10082]

  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/workers-sdk/issues/new/choose

```

it looks like the worker itself + code got deployed, but when i try to visit the url i just get the below

<img width="1219" alt="image" src="https://github.com/user-attachments/assets/4bbd2f6c-c499-4055-b99b-59f6c06c4179">

**Comment by DudeThatsErin** [comment]
Nameservers do have to point to cloudflare. You can still use AWS for other things just use A-Records for AWS or whatever via CloudFlare. Cloudflare has to handle the DNS for the worker to, well, work.

**Comment by skilbjo** [comment]
thanks v much. closing this issue as it seems like just a constraint rather than an issue.

regarding your answer though, do you know why that is? why can't it just work with a CNAME pointing to the worker url ?
