### ISSUE TITLE
Is it able to hide the original notion page slug?

### ISSUE THREAD

**Issue by phith0n** [velsa/notehost#7]
Hi,

Great project!

I have a question, is it able to hide the original notion page id?

For example, I'd like to allow only authenticated users to visit my Notion page by adding gateway in front of my domain.

But currently, visitors still are able to find the page slug from HTML:

![image](https://github.com/velsa/notehost/assets/5711185/536b1306-3c7c-4217-be6c-95556222f4ce)

Then they can use the original link to see the page: <https://velsa.notion.site/velsa/Velsa-net-4548c8872cd94297a61d35d90b7e54dd>

**Comment by velsa** [comment]
In order for the slugs to appear correctly in the browser address bar the script needs to know page IDs and slugs, because it will substitute one for the other. 

So the best approach would be to integrate auth verification in `src/reverse-proxy.ts`.
